[package]
name = "kv-rs"
description = "A distributed kv storage"
version = "0.1.0"
authors = ["fengyang <yueny09@163.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "~1.3.3"
clap = { version = "~4.4.2", features = ["cargo"] }
log = "~0.4.14"
serde =  { version = "~1.0.126", features = ["derive"] }
serde_json = "1.0"
serde_bytes = "~0.11.12"
serde_derive = "~1.0.126"
bytes = "1.5.0"
byteorder = "1.5.0"
fs4 = "~0.7.0"
tokio = { version = "~1.35.1", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "net",
    "io-util",
    "time",
    "sync",
] }
tokio-serde = { version = "~0.8", features = ["bincode"] }
tokio-stream = { version = "~0.1.6", features = ["net"] }
tokio-util = { version = "~0.7.8", features = ["codec"] }

[dev-dependencies]
tempdir = "~0.3.7"
tempfile = "~3.9.0"
