version: 1
api_key : "abcd"

# data directory, and the garbage ratio threshold at which to trigger kvd b compaction when opening the kvdb (only LogCask).
data_dir : "/media/fengyang/App-1T/workspace/kv/storage"
compact_threshold: 0.2

show_affected : false
show_progress : false